# Generated by Django 5.1.6 on 2025-08-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Full Stack')], default='fullstack', max_length=50),
        ),
    ]
