# Generated by Django 5.1.6 on 2025-07-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_socialmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tags',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='project',
            name='detail',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
