# Generated by Django 5.1.6 on 2025-07-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_rename_tags_project_summary_project_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technology',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
