# Generated by Django 5.1.6 on 2025-07-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_alter_project_options_alter_socialmedia_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='detail',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
