# Generated by Django 5.1.6 on 2025-08-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_project_image2_project_image3_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image3',
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], default='frontend', max_length=50),
        ),
    ]
