# Generated by Django 5.1.6 on 2025-08-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_remove_project_summary_remove_socialmedia_image_and_more'),
        ('portfolio_app', '0013_remove_summary_field'),
    ]

    operations = [
    ]
